In [1]:
from core.data_structures.core_data import CoreData
import numpy as np

In [2]:
# Example usage
data = CoreData([[1, 2, 3], [4, 5, 6]], dims=("rows", "columns"))
print(data)
print(type(data))
print(data.dims)
print(data.get_dim(1))
print(data.get_axis("columns"))


[[1 2 3]
 [4 5 6]]
<class 'core.data_structures.core_data.CoreData'>
('rows', 'columns')
columns
1


In [3]:
# Slicing
sliced_data = data[:, 1:]
print(sliced_data)
print(type(sliced_data))
print(sliced_data.dims)


[[2 3]
 [5 6]]
<class 'core.data_structures.core_data.CoreData'>
('rows', 'columns')


In [4]:
# Summing in place
data += 1
print(data)
print(type(data))
print(data.dims)


[[2 3 4]
 [5 6 7]]
<class 'core.data_structures.core_data.CoreData'>
('rows', 'columns')


In [5]:
# Extracting a submatrix
submatrix = data[0, :]
print(submatrix)
print(type(submatrix))
print(submatrix.dims)

[2 3 4]
<class 'core.data_structures.core_data.CoreData'>
('',)


In [6]:
# Transposing via the T attribute
transposed_data = data.T
print(transposed_data)
print(type(transposed_data))
print(transposed_data.dims)

# Transposing via the transpose method
transposed_data = data.transpose()
print(transposed_data)
print(type(transposed_data))
print(transposed_data.dims)

[[2 5]
 [3 6]
 [4 7]]
<class 'core.data_structures.core_data.CoreData'>
('columns', 'rows')
[[2 5]
 [3 6]
 [4 7]]
<class 'core.data_structures.core_data.CoreData'>
('columns', 'rows')


In [7]:
# Swap axes
swapped_data = data.swapaxes(0,1)
print(swapped_data)
print(type(swapped_data))
print(swapped_data.dims)

[[2 5]
 [3 6]
 [4 7]]
<class 'core.data_structures.core_data.CoreData'>
('columns', 'rows')


In [11]:
# Index a regular numpy array using a custom object
indexer = CoreData([1, 3], dims=("rows",))
numpy_array = np.array([1, 2, 3, 4, 5, 6, 7])
result = numpy_array[indexer]
print(numpy_array)
print(result)
print(type(result))

[1 2 3 4 5 6 7]
[2 4]
<class 'numpy.ndarray'>


In [12]:
# Index a regular numpy array using a custom object used as a condition (to produce a boolean mask)
obj = CoreData([1, 2, 3, 4, 5, 6, 7], dims=("rows",))
mask = obj > 3
print(mask)
print(type(mask))
print(mask.dims)
result = numpy_array[mask]
print(result)
print(type(result))


[False False False  True  True  True  True]
<class 'core.data_structures.core_data.CoreData'>
('rows',)
[4 5 6 7]
<class 'numpy.ndarray'>
